const express = require("express");
const { runPlanner } = require("../agents/planner");
const { runDeveloper } = require("../agents/developer");
const { runReviewer } = require("../agents/reviewer");
const { runTester } = require("../agents/tester");

const router = express.Router();

/**
 * POST /api/agent/run
 * Body: { requirement: string, language: string }
 *
 * Orchestrates: requirement -> planner -> developer -> reviewer -> tester -> final result
 */
router.post("/run", async (req, res) => {
  try {
    const { requirement, language } = req.body;

    if (!requirement || typeof requirement !== "string" || !requirement.trim()) {
      return res.status(400).json({ error: "A non-empty 'requirement' string is required." });
    }
    if (!language || typeof language !== "string") {
      return res.status(400).json({ error: "A 'language' string is required." });
    }

    // Step 1: Planner
    const plannerResult = await runPlanner(requirement, language);

    // Step 2: Developer
    const developerResult = await runDeveloper(requirement, language, plannerResult.plan);

    // Step 3: Reviewer
    const reviewerResult = await runReviewer(requirement, language, developerResult.code);

    // Step 4: Tester
    const testerResult = await runTester(requirement, language, developerResult.code);

    const usedMock = [plannerResult, developerResult, reviewerResult, testerResult].some(
      (r) => r.mode === "mock"
    );

    const finalSolution = [
      `# Final Solution`,
      ``,
      `**Requirement:** ${requirement}`,
      `**Language:** ${language}`,
      ``,
      `This solution was generated by the DevAgent pipeline (Planner -> Developer -> Reviewer -> Tester).`,
      developerResult.explanation ? `\n**Summary:** ${developerResult.explanation}` : "",
    ]
      .filter(Boolean)
      .join("\n");

    return res.json({
      requirement,
      language,
      plan: plannerResult.plan,
      code: developerResult.code,
      explanation: developerResult.explanation,
      files: developerResult.files,
      review: reviewerResult.review,
      tests: testerResult.tests,
      finalSolution,
      demoMode: usedMock,
    });
  } catch (err) {
    console.error("Agent pipeline error:", err);
    return res.status(500).json({
      error: "The AI agent pipeline failed unexpectedly.",
      details: err.message,
    });
  }
});

module.exports = router;
